### PR TITLE
Update "code style" section focusing on automated code formatting

### PR DESCRIPTION
**Pull request by arturkot**
Hello 👋 

this PR is all about _automated code formatting_.

* I'm trying to put emphasis on using code editor/IDE plugins to make the job done.
* Also, passing few useful tips (hopefully!) regarding Eslint & Prettier.
* I wonder if we should keep "Line endings" section?

Cheers,

Artur

### CODE REVIEW

**Comment by luboskmetko** [comment]
@arturkot I cannot fully judge the technical side, but the general approach looks good to me. The only thing which was a bit unclear to me is if this could be used on non-Chisel projects - I assume that part `or eslint-config-airbnb with eslint-config-prettier.`  relates to that? If so, maybe I would make it clearer like _Use eslint-config-chisel on Chisel projects and eslint-config-airbnb with eslint-config-prettier on non-Chisel projects_

**Comment by jakub300** [comment]
Hi @arturkot,
1. you're confusing `eslint-plugin-prettier` and `eslint-config-prettier`. Config is only responsible for disabling potentially conflicting rules, not for formatting. Plugin is necessary for that.
2. I think when Prettier is used with ESLint there is no need (for JS/TS) to use Prettier in your IDE because you're running it twice.
3. `Eslint` -> `ESLint`.
4. there is some inconsistency with languaage, some points start with capital letter and end with dot, some don't.

**Comment by jakub300** [comment]
5. Update Link to Chisel ESLint config to permalink, we'll update to master after release.

**Comment by arturkot** [comment]
Thanks for the feedback! 👍 

> The only thing which was a bit unclear to me is if this could be used on non-Chisel projects - I assume that part or eslint-config-airbnb with eslint-config-prettier. relates to that? If so, maybe I would make it clearer like Use eslint-config-chisel on Chisel projects and eslint-config-airbnb with eslint-config-prettier on non-Chisel projects

> you're confusing eslint-plugin-prettier and eslint-config-prettier. Config is only responsible for disabling potentially conflicting rules, not for formatting. Plugin is necessary for that.

I removed the whole text regarding `eslint-config` files and added a point regarding Chisel projects. See: https://github.com/xfiveco/js-coding-standards/pull/2/commits/534776ffcf7b44f3e5fce33ad7623850ed1c11b9

> I think when Prettier is used with ESLint there is no need (for JS/TS) to use Prettier in your IDE because you're running it twice.

In general I agree. It's enough to run ESLint auto fix to get rid of most of the problems which are easy to fix. I attempted to explain the general differences between ESLint and Prettier and suggested ESLint as the default choice. LMK your thoughts. Perhaps it's better to get rid all those Prettier related comments for the sake of simplicity?

<details>
<summary>However, I've noticed I prefer to run Prettier way more often. It's definitely a personal preference.</summary>

I keep Prettier under a keyboard shortcut and run it very often because it's _fast_. Feels almost as responsive as hitting a tab to adjust nesting. Then, I run Eslint from time to time to deal with things like sorting imports or anything else which can fall beyond Prettier's capabilities. The thing is Eslint takes around 1 second to auto fix/format code (or at least this is how it _feels_) so I avoid using it too often.
</details>

> `Eslint` -> `ESLint`.

Should be fixed. LMK in case there's more typos or mistakes. 👍 

> there is some inconsistency with languaage, some points start with capital letter and end with dot, some don't.

I've noticed 2 paragraphs: https://github.com/xfiveco/js-coding-standards/pull/2/commits/e1e9211b2352a8358845387e6ee7845fcad3f8bd

> Update Link to Chisel ESLint config to permalink, we'll update to master after release.

Done: https://github.com/xfiveco/js-coding-standards/pull/2/commits/4d6391fec108b90a0f435b27eb1f8e57e2caf421 I always trip on that. 🙄

**Comment by KamWis** [comment]
@luboskmetko @arturkot @jakub300   Can we merge this?

**Comment by arturkot** [comment]
cc @luboskmetko @jakub300 

@KamWis I'd say: let's merge it. :P

**Comment by arturkot** [comment]
Closing as it's probably irrelevant by now and it occupies my to-do list on GH. :P

**Pull request closed without merging**
